/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  containsBytes,
  getU8Encoder,
  type Address,
  type ReadonlyUint8Array,
} from '@solana/kit';
import {
  type ParsedCreateTokenInstruction,
  type ParsedInitMintAuthorityInstruction,
  type ParsedMintTokenInstruction,
} from '../instructions';

export const PDA_MINT_AUTHORITY_PROGRAM_ADDRESS =
  '5JTY1h4jWJ2JfoJMxNtr6J9T1PkT2aP5mVTBm72UAhzf' as Address<'5JTY1h4jWJ2JfoJMxNtr6J9T1PkT2aP5mVTBm72UAhzf'>;

export enum PdaMintAuthorityInstruction {
  InitMintAuthority,
  CreateToken,
  MintToken,
}

export function identifyPdaMintAuthorityInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): PdaMintAuthorityInstruction {
  const data = 'data' in instruction ? instruction.data : instruction;
  if (containsBytes(data, getU8Encoder().encode(0), 0)) {
    return PdaMintAuthorityInstruction.InitMintAuthority;
  }
  if (containsBytes(data, getU8Encoder().encode(1), 0)) {
    return PdaMintAuthorityInstruction.CreateToken;
  }
  if (containsBytes(data, getU8Encoder().encode(2), 0)) {
    return PdaMintAuthorityInstruction.MintToken;
  }
  throw new Error(
    'The provided instruction could not be identified as a pdaMintAuthority instruction.',
  );
}

export type ParsedPdaMintAuthorityInstruction<
  TProgram extends string = '5JTY1h4jWJ2JfoJMxNtr6J9T1PkT2aP5mVTBm72UAhzf',
> =
  | ({
      instructionType: PdaMintAuthorityInstruction.InitMintAuthority;
    } & ParsedInitMintAuthorityInstruction<TProgram>)
  | ({
      instructionType: PdaMintAuthorityInstruction.CreateToken;
    } & ParsedCreateTokenInstruction<TProgram>)
  | ({
      instructionType: PdaMintAuthorityInstruction.MintToken;
    } & ParsedMintTokenInstruction<TProgram>);
