/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type TransactionSigner,
  type WritableSignerAccount,
} from '@solana/kit';
import { TOKEN2022_BASIC_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const CREATE_TOKEN_DISCRIMINATOR = 0;

export function getCreateTokenDiscriminatorBytes() {
  return getU8Encoder().encode(CREATE_TOKEN_DISCRIMINATOR);
}

export type CreateTokenInstruction<
  TProgram extends string = typeof TOKEN2022_BASIC_PROGRAM_ADDRESS,
  TAccountPayer extends string | IAccountMeta<string> = string,
  TAccountMint extends string | IAccountMeta<string> = string,
  TAccountTokenProgram extends
    | string
    | IAccountMeta<string> = 'TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb',
  TAccountSystemProgram extends
    | string
    | IAccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            IAccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountMint extends string
        ? WritableSignerAccount<TAccountMint> & IAccountSignerMeta<TAccountMint>
        : TAccountMint,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type CreateTokenInstructionData = {
  discriminator: number;
  /** The name of the user to create */
  tokenName: string;
  /** The number of decimals for the token. */
  tokenDecimals: number;
};

export type CreateTokenInstructionDataArgs = {
  /** The name of the user to create */
  tokenName: string;
  /** The number of decimals for the token. */
  tokenDecimals: number;
};

export function getCreateTokenInstructionDataEncoder(): Encoder<CreateTokenInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', getU8Encoder()],
      ['tokenName', fixEncoderSize(getUtf8Encoder(), 32)],
      ['tokenDecimals', getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: 0 }),
  );
}

export function getCreateTokenInstructionDataDecoder(): Decoder<CreateTokenInstructionData> {
  return getStructDecoder([
    ['discriminator', getU8Decoder()],
    ['tokenName', fixDecoderSize(getUtf8Decoder(), 32)],
    ['tokenDecimals', getU8Decoder()],
  ]);
}

export function getCreateTokenInstructionDataCodec(): Codec<
  CreateTokenInstructionDataArgs,
  CreateTokenInstructionData
> {
  return combineCodec(
    getCreateTokenInstructionDataEncoder(),
    getCreateTokenInstructionDataDecoder(),
  );
}

export type CreateTokenInput<
  TAccountPayer extends string = string,
  TAccountMint extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** The payer of the transaction */
  payer: TransactionSigner<TAccountPayer>;
  /** The mint account that will be created */
  mint: TransactionSigner<TAccountMint>;
  /** The token program that will handle the mint */
  tokenProgram?: Address<TAccountTokenProgram>;
  /** System Program used to open our new account */
  systemProgram?: Address<TAccountSystemProgram>;
  tokenName: CreateTokenInstructionDataArgs['tokenName'];
  tokenDecimals: CreateTokenInstructionDataArgs['tokenDecimals'];
};

export function getCreateTokenInstruction<
  TAccountPayer extends string,
  TAccountMint extends string,
  TAccountTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof TOKEN2022_BASIC_PROGRAM_ADDRESS,
>(
  input: CreateTokenInput<
    TAccountPayer,
    TAccountMint,
    TAccountTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): CreateTokenInstruction<
  TProgramAddress,
  TAccountPayer,
  TAccountMint,
  TAccountTokenProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? TOKEN2022_BASIC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: true },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb' as Address<'TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb'>;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.payer),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getCreateTokenInstructionDataEncoder().encode(
      args as CreateTokenInstructionDataArgs,
    ),
  } as CreateTokenInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountMint,
    TAccountTokenProgram,
    TAccountSystemProgram
  >;

  return instruction;
}

export type ParsedCreateTokenInstruction<
  TProgram extends string = typeof TOKEN2022_BASIC_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** The payer of the transaction */
    payer: TAccountMetas[0];
    /** The mint account that will be created */
    mint: TAccountMetas[1];
    /** The token program that will handle the mint */
    tokenProgram: TAccountMetas[2];
    /** System Program used to open our new account */
    systemProgram: TAccountMetas[3];
  };
  data: CreateTokenInstructionData;
};

export function parseCreateTokenInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>,
): ParsedCreateTokenInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      payer: getNextAccount(),
      mint: getNextAccount(),
      tokenProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getCreateTokenInstructionDataDecoder().decode(instruction.data),
  };
}
