/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  containsBytes,
  getU8Encoder,
  type Address,
  type ReadonlyUint8Array,
} from '@solana/kit';
import {
  type ParsedCreateTokenInstruction,
  type ParsedMintTokenInstruction,
  type ParsedTransferInstruction,
} from '../instructions';

export const TRANSFER_TOKENS_PROGRAM_ADDRESS =
  '48njBs5KjS8fQp4LF2QCo2V7G5vjwnmFGiAYDKkYzkZa' as Address<'48njBs5KjS8fQp4LF2QCo2V7G5vjwnmFGiAYDKkYzkZa'>;

export enum TransferTokensInstruction {
  CreateToken,
  MintToken,
  Transfer,
}

export function identifyTransferTokensInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): TransferTokensInstruction {
  const data = 'data' in instruction ? instruction.data : instruction;
  if (containsBytes(data, getU8Encoder().encode(0), 0)) {
    return TransferTokensInstruction.CreateToken;
  }
  if (containsBytes(data, getU8Encoder().encode(1), 0)) {
    return TransferTokensInstruction.MintToken;
  }
  if (containsBytes(data, getU8Encoder().encode(2), 0)) {
    return TransferTokensInstruction.Transfer;
  }
  throw new Error(
    'The provided instruction could not be identified as a transferTokens instruction.',
  );
}

export type ParsedTransferTokensInstruction<
  TProgram extends string = '48njBs5KjS8fQp4LF2QCo2V7G5vjwnmFGiAYDKkYzkZa',
> =
  | ({
      instructionType: TransferTokensInstruction.CreateToken;
    } & ParsedCreateTokenInstruction<TProgram>)
  | ({
      instructionType: TransferTokensInstruction.MintToken;
    } & ParsedMintTokenInstruction<TProgram>)
  | ({
      instructionType: TransferTokensInstruction.Transfer;
    } & ParsedTransferInstruction<TProgram>);
