/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { PDA_MINT_AUTHORITY_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const INIT_MINT_AUTHORITY_DISCRIMINATOR = 0;

export function getInitMintAuthorityDiscriminatorBytes() {
  return getU8Encoder().encode(INIT_MINT_AUTHORITY_DISCRIMINATOR);
}

export type InitMintAuthorityInstruction<
  TProgram extends string = typeof PDA_MINT_AUTHORITY_PROGRAM_ADDRESS,
  TAccountPayer extends string | IAccountMeta<string> = string,
  TAccountMintAuthority extends string | IAccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | IAccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            IAccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountMintAuthority extends string
        ? WritableAccount<TAccountMintAuthority>
        : TAccountMintAuthority,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type InitMintAuthorityInstructionData = {
  discriminator: number;
  /** The bump seed for the mint authority PDA. */
  bump: number;
};

export type InitMintAuthorityInstructionDataArgs = {
  /** The bump seed for the mint authority PDA. */
  bump: number;
};

export function getInitMintAuthorityInstructionDataEncoder(): Encoder<InitMintAuthorityInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', getU8Encoder()],
      ['bump', getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: 0 }),
  );
}

export function getInitMintAuthorityInstructionDataDecoder(): Decoder<InitMintAuthorityInstructionData> {
  return getStructDecoder([
    ['discriminator', getU8Decoder()],
    ['bump', getU8Decoder()],
  ]);
}

export function getInitMintAuthorityInstructionDataCodec(): Codec<
  InitMintAuthorityInstructionDataArgs,
  InitMintAuthorityInstructionData
> {
  return combineCodec(
    getInitMintAuthorityInstructionDataEncoder(),
    getInitMintAuthorityInstructionDataDecoder(),
  );
}

export type InitMintAuthorityInput<
  TAccountPayer extends string = string,
  TAccountMintAuthority extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** The payer of the transaction */
  payer: TransactionSigner<TAccountPayer>;
  /** The PDA mint authority account that will be created */
  mintAuthority: Address<TAccountMintAuthority>;
  /** System Program used to open our new account */
  systemProgram?: Address<TAccountSystemProgram>;
  bump: InitMintAuthorityInstructionDataArgs['bump'];
};

export function getInitMintAuthorityInstruction<
  TAccountPayer extends string,
  TAccountMintAuthority extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof PDA_MINT_AUTHORITY_PROGRAM_ADDRESS,
>(
  input: InitMintAuthorityInput<
    TAccountPayer,
    TAccountMintAuthority,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): InitMintAuthorityInstruction<
  TProgramAddress,
  TAccountPayer,
  TAccountMintAuthority,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? PDA_MINT_AUTHORITY_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    mintAuthority: { value: input.mintAuthority ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.payer),
      getAccountMeta(accounts.mintAuthority),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getInitMintAuthorityInstructionDataEncoder().encode(
      args as InitMintAuthorityInstructionDataArgs,
    ),
  } as InitMintAuthorityInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountMintAuthority,
    TAccountSystemProgram
  >;

  return instruction;
}

export type ParsedInitMintAuthorityInstruction<
  TProgram extends string = typeof PDA_MINT_AUTHORITY_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** The payer of the transaction */
    payer: TAccountMetas[0];
    /** The PDA mint authority account that will be created */
    mintAuthority: TAccountMetas[1];
    /** System Program used to open our new account */
    systemProgram: TAccountMetas[2];
  };
  data: InitMintAuthorityInstructionData;
};

export function parseInitMintAuthorityInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>,
): ParsedInitMintAuthorityInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      payer: getNextAccount(),
      mintAuthority: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getInitMintAuthorityInstructionDataDecoder().decode(instruction.data),
  };
}
