/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  containsBytes,
  getU8Encoder,
  type Address,
  type ReadonlyUint8Array,
} from '@solana/kit';
import {
  type ParsedCreatePdaInstruction,
  type ParsedGetPdaInstruction,
} from '../instructions';

export const FAVORITES_PROGRAM_ADDRESS =
  '21cBfH1aaKVeq86icK5pq51FM3ak2QQJ1TWoMLcTTK34' as Address<'21cBfH1aaKVeq86icK5pq51FM3ak2QQJ1TWoMLcTTK34'>;

export enum FavoritesAccount {
  Favorites,
}

export function identifyFavoritesAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): FavoritesAccount {
  const data = 'data' in account ? account.data : account;
  if (containsBytes(data, getU8Encoder().encode(0), 0)) {
    return FavoritesAccount.Favorites;
  }
  throw new Error(
    'The provided account could not be identified as a favorites account.',
  );
}

export enum FavoritesInstruction {
  CreatePda,
  GetPda,
}

export function identifyFavoritesInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): FavoritesInstruction {
  const data = 'data' in instruction ? instruction.data : instruction;
  if (containsBytes(data, getU8Encoder().encode(0), 0)) {
    return FavoritesInstruction.CreatePda;
  }
  if (containsBytes(data, getU8Encoder().encode(1), 0)) {
    return FavoritesInstruction.GetPda;
  }
  throw new Error(
    'The provided instruction could not be identified as a favorites instruction.',
  );
}

export type ParsedFavoritesInstruction<
  TProgram extends string = '21cBfH1aaKVeq86icK5pq51FM3ak2QQJ1TWoMLcTTK34',
> =
  | ({
      instructionType: FavoritesInstruction.CreatePda;
    } & ParsedCreatePdaInstruction<TProgram>)
  | ({
      instructionType: FavoritesInstruction.GetPda;
    } & ParsedGetPdaInstruction<TProgram>);
