/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { TRANSFER_SOL_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const TRANSFER_SOL_WITH_CPI_DISCRIMINATOR = 1;

export function getTransferSolWithCpiDiscriminatorBytes() {
  return getU8Encoder().encode(TRANSFER_SOL_WITH_CPI_DISCRIMINATOR);
}

export type TransferSolWithCpiInstruction<
  TProgram extends string = typeof TRANSFER_SOL_PROGRAM_ADDRESS,
  TAccountPayer extends string | IAccountMeta<string> = string,
  TAccountRecipient extends string | IAccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | IAccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            IAccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountRecipient extends string
        ? WritableAccount<TAccountRecipient>
        : TAccountRecipient,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type TransferSolWithCpiInstructionData = {
  discriminator: number;
  /** The amount of SOL to transfer */
  amount: bigint;
};

export type TransferSolWithCpiInstructionDataArgs = {
  /** The amount of SOL to transfer */
  amount: number | bigint;
};

export function getTransferSolWithCpiInstructionDataEncoder(): Encoder<TransferSolWithCpiInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', getU8Encoder()],
      ['amount', getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: 1 }),
  );
}

export function getTransferSolWithCpiInstructionDataDecoder(): Decoder<TransferSolWithCpiInstructionData> {
  return getStructDecoder([
    ['discriminator', getU8Decoder()],
    ['amount', getU64Decoder()],
  ]);
}

export function getTransferSolWithCpiInstructionDataCodec(): Codec<
  TransferSolWithCpiInstructionDataArgs,
  TransferSolWithCpiInstructionData
> {
  return combineCodec(
    getTransferSolWithCpiInstructionDataEncoder(),
    getTransferSolWithCpiInstructionDataDecoder(),
  );
}

export type TransferSolWithCpiInput<
  TAccountPayer extends string = string,
  TAccountRecipient extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** The account that will pay for the transaction */
  payer: TransactionSigner<TAccountPayer>;
  /** The account that will receive the SOL */
  recipient: Address<TAccountRecipient>;
  /** System Program used to open our new account */
  systemProgram?: Address<TAccountSystemProgram>;
  amount: TransferSolWithCpiInstructionDataArgs['amount'];
};

export function getTransferSolWithCpiInstruction<
  TAccountPayer extends string,
  TAccountRecipient extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof TRANSFER_SOL_PROGRAM_ADDRESS,
>(
  input: TransferSolWithCpiInput<
    TAccountPayer,
    TAccountRecipient,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): TransferSolWithCpiInstruction<
  TProgramAddress,
  TAccountPayer,
  TAccountRecipient,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? TRANSFER_SOL_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    recipient: { value: input.recipient ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.payer),
      getAccountMeta(accounts.recipient),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getTransferSolWithCpiInstructionDataEncoder().encode(
      args as TransferSolWithCpiInstructionDataArgs,
    ),
  } as TransferSolWithCpiInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountRecipient,
    TAccountSystemProgram
  >;

  return instruction;
}

export type ParsedTransferSolWithCpiInstruction<
  TProgram extends string = typeof TRANSFER_SOL_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** The account that will pay for the transaction */
    payer: TAccountMetas[0];
    /** The account that will receive the SOL */
    recipient: TAccountMetas[1];
    /** System Program used to open our new account */
    systemProgram: TAccountMetas[2];
  };
  data: TransferSolWithCpiInstructionData;
};

export function parseTransferSolWithCpiInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>,
): ParsedTransferSolWithCpiInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      payer: getNextAccount(),
      recipient: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getTransferSolWithCpiInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
