/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  containsBytes,
  getU8Encoder,
  type Address,
  type ReadonlyUint8Array,
} from '@solana/kit';
import {
  type ParsedCreateInstruction,
  type ParsedDecreaseInstruction,
  type ParsedIncreaseInstruction,
} from '../instructions';

export const CROSS_PROGRAM_INVOCATION_PROGRAM_ADDRESS =
  'HgeJhsevaynVUxZdwD5RJxuubfMagRmfkj9dHDHidwVY' as Address<'HgeJhsevaynVUxZdwD5RJxuubfMagRmfkj9dHDHidwVY'>;

export enum CrossProgramInvocationInstruction {
  Create,
  Increase,
  Decrease,
}

export function identifyCrossProgramInvocationInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): CrossProgramInvocationInstruction {
  const data = 'data' in instruction ? instruction.data : instruction;
  if (containsBytes(data, getU8Encoder().encode(0), 0)) {
    return CrossProgramInvocationInstruction.Create;
  }
  if (containsBytes(data, getU8Encoder().encode(1), 0)) {
    return CrossProgramInvocationInstruction.Increase;
  }
  if (containsBytes(data, getU8Encoder().encode(1), 0)) {
    return CrossProgramInvocationInstruction.Decrease;
  }
  throw new Error(
    'The provided instruction could not be identified as a crossProgramInvocation instruction.',
  );
}

export type ParsedCrossProgramInvocationInstruction<
  TProgram extends string = 'HgeJhsevaynVUxZdwD5RJxuubfMagRmfkj9dHDHidwVY',
> =
  | ({
      instructionType: CrossProgramInvocationInstruction.Create;
    } & ParsedCreateInstruction<TProgram>)
  | ({
      instructionType: CrossProgramInvocationInstruction.Increase;
    } & ParsedIncreaseInstruction<TProgram>)
  | ({
      instructionType: CrossProgramInvocationInstruction.Decrease;
    } & ParsedDecreaseInstruction<TProgram>);
